### ISSUE TITLE
example webapp usage of soft-webauthn?

### ISSUE THREAD

**Issue by equalsJeffH** [bodik/soft-webauthn#1]
@bodik: 
you write in README.md:
> Package is used for testing webauthn enabled web applications

could you please provide a brief code example of how one would actually use soft-webauthn from a webapp?

thanks!

**Comment by bodik** [comment]
Sure @equalsJeffH. Would you mind to review the updates in dev branch ?

* https://github.com/bodik/soft-webauthn/blob/dev-01-better_api/README.md
* https://github.com/bodik/soft-webauthn/blob/dev-01-better_api/tests/test_example.py

**Comment by bodik** [comment]
FYI it's merged anyway. I'll just leave it open cause I'd like to have you review someday

**Comment by equalsJeffH** [comment]
Ok, thx @bodik,

So if I understand correctly: `test_example.py` is an illustration of how one can use soft_webauthn to emulate the client-side of a webapp running in a browser having a WebAuthn/FIDO2 authenticator available.  Thus as presently constituted, it is mostly useful for exercising the server-side of a webapp.

If one wishes to use soft_webauthn to test the server-side of their webapp, they _could_ use tests/test_example.py as a starting point.

Yes?

**Comment by bodik** [comment]
> Thus as presently constituted, it is mostly useful for exercising the server-side of a webapp.
> 
> If one wishes to use soft_webauthn to test the server-side of their webapp, they _could_ use 
> tests/test_example.py as a starting point.
> 
> Yes?

exactly

**Comment by bodik** [comment]
released better documentation as new version (because of pypi upload)
