### ISSUE TITLE
Fix attestation format

### ISSUE THREAD

**Issue by sstoel** [bodik/soft-webauthn#5]
If 'fmt' is packed there should be values in 'attStmt'. This can cause certain servers to fail the registration (webauthn4j for example)

https://github.com/bodik/soft-webauthn/pull/4

**Comment by bodik** [comment]
hi, thank you for your contribution. I've merged PR in off-the-github repository, hopefully i've not messed up with master too much (i promise to behave better next time ;)

I'd wait few more days if there are other issues found before releasing fixed version to pypi.

**Comment by bodik** [comment]
released in v0.1.1
