### ISSUE TITLE
Need to fix challenge in clientDataJSON

### ISSUE THREAD

**Issue by kverdecia** [bodik/soft-webauthn#8]
The webauthn specification for the `challenge` attribute in `clientDataJSON` doesn't contains the trailing `=` characters:

[https://w3c.github.io/webauthn/#base64url-encoding](https://w3c.github.io/webauthn/#base64url-encoding)

In the methods `create` `and` get methods of the class `SoftWebauthnDevice` you use `base64.urlsafe_b64encode` that does returns the value with the trailing `=` characters.

I noticed this programming the unit tests for a django app where I'm using py-webauthn. This `=` characters at the end of the challenge value makes the tests fails. I temporally fixed this in my app inheriting from `SoftWebauthnDevice` and overriding this methods to remove the `=` character from the `challenge` attribute.

**Comment by kverdecia** [comment]
I made a PR with a fix for this issue. The solution is quite simple: [https://github.com/bodik/soft-webauthn/pull/9](https://github.com/bodik/soft-webauthn/pull/9)

**Comment by bodik** [comment]
Hello, thank you for the contribution. I've merged the PR and released new version 0.1.2.
